### ISSUE TITLE
What's the licence for the dataset?

### ISSUE THREAD

**Issue by stephenleo** [msadat3/SciNLI#1]
Hi, thanks for sharing this dataset. Have a couple of questions. Appreciate your reply.
1. May I check what's the license for the usage and sharing of this dataset?
2. Could you upload this dataset to Kaggle? Or do you want me to upload it with proper attribution to this repo and paper?

Thanks!

**Comment by msadat3** [comment]
Hello,

The dataset is licensed with Attribution-ShareAlike 4.0 International (CC BY-SA 4.0). We have just made it available on Kaggle.
